cluster/compropj/clienteapp/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views
#from clienteapp.views import about_view #para las clases
from clienteapp.views import RegistroView, user_view, cc_view, Compro_View

app_name='users_path'
urlpatterns = [
    path('',            views.landing_view,     name='landing_view'),
    #path('login/',      views.login_view,       name='login_view'),
    path('login/', auth_views.LoginView.as_view(template_name='clienteapp/login.html'), name='login'),
    #path('registro/',   views.registro_view,    name='registro_view'),
    path('registrar/',RegistroView.as_view(), name='registro_view'),
    #path('about/',    about_view.as_view(), name='about'),
    path('centrocomercial/', cc_view.as_view(), name='cc_view'),
    path('user/<int:pk>', user_view.as_view(), name='user_view'),
    #path('localadmin/',admin_view.as_view(), name='ladmin_view'),
    path('localadmin/',Compro_View.as_view(), name='compro_view'),
]

cluster/compropj/compropj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clienteapp.urls')),
]

cluster/compropj/clienteapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Centro_comercial(models.Model):
    nombre_centro = models.CharField(max_length=50)
    ciudad = models.CharField(max_length=20)
    direccion = models.CharField(max_length=20)
    def __str__(self):
        return "{0}, {1}".format(self.nombre_centro,self.ciudad)

class Area_local(models.Model):
    inscripcion_cc = models.ForeignKey(Centro_comercial,null=True, blank=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    ubicacion=models.PositiveSmallIntegerField()
    coordenadas = models.CharField(max_length=100)
    def __str__(self):
        return "{0}, {1}".format(self.nombre, self.inscripcion_cc)

class Combos_promos(models.Model):
    compros = models.ForeignKey(Area_local,null=True, blank=True, on_delete=models.CASCADE)
    nombre=models.CharField(max_length=100,  default='Mi primer combo')
    descripcion=models.CharField(max_length=100)
    release_date = models.DateField()
    def __str__(self):
        return "{0}, {1}".format(self.nombre, self.compros)
    
'''Una cosa es el nombre, y otra el usuario
Para el caso del usuario es la clave con la que un cc/local se logea.
Para el caso del nombre, es la clave que permite diferenciarlos'''
class Perfil(models.Model):
    user    =   models.OneToOneField(User,on_delete=models.CASCADE)
    eslocal =   models.OneToOneField(Area_local,on_delete=models.CASCADE ,null=True, blank=True)
    escc    =   models.OneToOneField(Centro_comercial,on_delete=models.CASCADE, null=True, blank=True)
    nombre  =   models.CharField(max_length=100 )

cluster/compropj/clienteapp/forms.py
from django import forms
from django.contrib.auth.models import User #para registrar usuarios.
from django.forms import ModelForm, TextInput, NumberInput, ChoiceField, Textarea, Select, FileInput
from .models import Combos_promos, Area_local
class registrar_usuario_form(forms.Form):
    usuario =   forms.CharField(widget=forms.TextInput(attrs={'class':'input100'}))
    correo  =   forms.EmailField(widget=forms.TextInput(attrs={'class':'input100'}))
    password_1  =  forms.CharField(label='Password',widget=forms.PasswordInput(render_value=False,attrs={'class':'input100'}))
    password_2  =  forms.CharField(label='Confirmar Password',widget=forms.PasswordInput(render_value=False,attrs={'class':'input100'}))
    
class registrar_compro_form(forms.Form):
    #adscrito =forms.ForeingKey()
    adscrito = forms.ModelChoiceField(queryset=Area_local.objects.all()) #aqui se hace un filtro.
    nombre =   forms.CharField(widget=forms.TextInput(attrs={'class':'input100' ,'placeholder':'Un título genial!'}))
    descripcion =forms.CharField(widget=forms.TextInput(attrs={'class':'textarea','placeholder':'Descripción'}))
    #foto=forms.ImageField()
        

cluster/compropj/clienteapp/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from .forms import registrar_usuario_form, registrar_compro_form   #para registrar users 1 y compros
from django.views.generic import FormView   #para registrar users 2
from django.contrib.auth.models import User #para registrar users 3
from django.views.generic.base import TemplateView #para ver templates con contexto

#para usar el decorador
from django.contrib.auth.decorators import login_required

#para la fecha
from datetime import datetime

from django.http import HttpResponse, HttpResponseRedirect

from .models import *

# Create your views here.
def landing_view(request):
    return render(request,'clienteapp/landing.html')

def login_view(request):
    return render(request,'clienteapp/login.html')

def logout(request):
    pass

def registro_view(request):
    return render(request, 'clienteapp/registro.html')

#/centrocomercial/
#estado:90%
class cc_view(TemplateView):
    template_name = "clienteapp/cc_view.html"
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['ccs']=Centro_comercial.objects.all()
        context['locales']=Area_local.objects.all()
        print(context)
        return context
    
    '''cc debe ver todos los locales registrados y debe poder agregar locales'''
    #formview

#/user/pk=pk
#estado:60%
'''Revela la informacion de un centro comercial en especifico'''
class user_view(TemplateView):
    template_name = "clienteapp/user_view.html"
    def get_context_data(self, pk, **kwargs):
        context=super().get_context_data(**kwargs)
        context['identificacion']=Centro_comercial.objects.get(id=pk) 
        print(context)
        return context
    #templateview
    '''user view debe solo poder ver los centros comerciales y puede filtrar por nombre y ciudad*proximamente'''

''' El centro comercial puede registrar con RegistrarView a los centros comerciales
Los centros comerciales son registrados por el administrador de la aplicacion, de tal modo,
tanto el centro comercial puede loguearse para registrar, como los locales para registrar sus combos.'''
#no impleentada
class cc_admin_view(FormView):
    template_name = "clienteapp/local_admin_view.html"
    form_class = registrar_compro_form
    success_url = '/localadmin/'
    
    def form_valid(self, form):
        elcompro=Combos_promos(adscrito=self.request.POST['usuario'], nombre=self.request.POST['correo'], password=self.request.POST['password_1'])
        elcompro.save()
        return super().form_valid(form)
    
    '''Admin view puede agregar promociones, segun su tarifa*proximamente puede publicar todos o una.'''
    #formview
    def get_context_data(self, pk, **kwargs):
        context=super().get_context_data(**kwargs)
        context['compros']=Combos_promos.objects.all() 
        print(context)
        return context


#localadmin/
'''
Revela todas las promociones'''

class Compro_View(FormView):
    template_name = 'clienteapp/local_admin_view.html'
    form_class = registrar_compro_form
    success_url="/"
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['compros']=Combos_promos.objects.all()
        print("Has llegado a compro view a context_data")
        print(context)
        print("-------------------------------------") 
        
        return context

    def form_valid(self, form):
        print("Has llegado a form valid")

        a=Area_local.objects.get(id=self.request.POST['adscrito'])
        print(a,type(self.request.POST['adscrito']))
        compro=Combos_promos(compros=a, nombre=self.request.POST['nombre'], descripcion=self.request.POST['descripcion'], release_date=datetime.now())
        print("Has llegado a compro view a form_valid")
        print(compro.compros, compro.nombre, compro.descripcion, compro.release_date)
        compro.save()
        return super().form_valid(form)

#completado 90%
#/registrar/

class RegistroView(FormView):
    
    template_name = 'clienteapp/registro.html'
    form_class = registrar_usuario_form
    success_url = '/'
    def form_valid(self, form):
        usr=User.objects.create_user(username=self.request.POST['usuario'], email=self.request.POST['correo'], password=self.request.POST['password_1'])
        usr.save()
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        #form.send_email()
        return super().form_valid(form)

cluster/compropj/clienteapp/templates/clienteapp/cc_view.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <title>Centros Comerciales</title>
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'clienteapp/images/fav_icon.png' %}">
        <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.css'>
        <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css'>
        <link rel="stylesheet" href="{% static 'clienteapp/css/kanban.css' %}">
    </head>
    <body>
        <nav class="navbar has-shadow">
            <div class="container">
                <div class="navbar-brand"><a class="navbar-item" href="../"><img src="http://bulma.io/images/bulma-logo.png" alt="Bulma: a modern CSS framework based on Flexbox"/></a>
                <div class="navbar-burger burger" data-target="navMenu"><span></span><span></span><span></span></div>
            </div>

            

            <div class="navbar-menu" id="navMenu">
                    
                <div class="navbar-end">
                        <span class="navbar-item"> 
                        {% if user.is_authenticated %}
                        <div> Bienvenido: {{ user}}   </div>
                        {% endif %}
                        
                    <div class="navbar-item has-dropdown is-hoverable"><a class="navbar-link">Account</a>
                    <div class="navbar-dropdown"><a class="navbar-item">Dashboard</a><a class="navbar-item">Profile</a><a class="navbar-item">Settings</a>
                    <hr class="navbar-divider" />
                    <div class="navbar-item">Logout</div>
                </div>
            </div>
        </div>
    </div>
</div>
</nav>
<!--
<section class="hero is-info">
<div class="hero-body">
    <div class="container">
        <div class="card">
            <div class="card-content">
                <div class="content">
                    <div class="control has-icons-left has-icons-right">
                        <input class="input is-large" type="search" placeholder="" /><span class="icon is-medium is-left"><i class="fa fa-search"></i></span><span class="icon is-medium is-right"><i class="fa fa-empire"></i></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</section> 
-->
<div class="box cta">
<div class="columns is-mobile is-centered">
    <div class="field is-grouped is-grouped-multiline">
        <div class="control" ><span class="tag is-warning is-large" > <a href="{% url 'users_path:compro_view' %}">Administrar</a></span></div>
        <div class="control"><span class="tag is-success is-large">En servicio</span></div>
        <div class="control"><span class="tag is-primary is-large">Proximamente</span></div>

<!-- <div class="control"><span class="tag is-link is-large">Link</span></div>
        <div class="control"><span class="tag is-success is-large">Success</span></div>
        <div class="control"><span class="tag is-black is-large">Black</span></div>
        <div class="control"><span class="tag is-warning is-large">Warning</span></div>
        <div class="control"><span class="tag is-danger is-large">Danger</span></div>
        <div class="control"><span class="tag is-info is-large">Info</span></div>
-->

    </div>
</div>
</div>
<section class="container">
<div class="columns is-mobile is-centered" id="sectioncontainer">
    {% for elemento in ccs %}
    <div class="column is-narrow">
        <article class="message is-success" >
            <div class="message-header" id="linktocc" > 
                <a href="{% url 'users_path:user_view' pk=elemento.id %}">{{ elemento }}</a>
                
                <button class="delete" aria-label="delete"></button>
            </div>
            
            <div class="message-body">

                {% for minielemento in locales %}
                {% if minielemento.inscripcion_cc.nombre_centro == elemento.nombre_centro %}
                <div class="board-item">
                        
                    <div class="board-item-content"><span>{{ minielemento.nombre }}</span></div>
                </div>
                {% endif %}
                {% endfor%}
                
            </div>

        </article>
    </div>
    {% endfor %}


    <div class="column is-narrow">
        <article class="message is-primary">
            <div class="message-header">
                <p>Proximos Centros Comerciales</p>
                <button class="delete" aria-label="delete"></button>
            </div>
            <div class="message-body">
                <div class="board-item">
                    <div class="board-item-content"><span> Santafé, Bogotá</span></div>
                </div>
                <div class="board-item">
                    <div class="board-item-content"><span> Andino, Bogotá</span></div>
                </div>
                <div class="board-item">
                    <div class="board-item-content"><span> Jardín Plaza, Cali</span></div>
                </div>
  
            </div>
        </article>
    </div>
    
</div>
</section>
<div class="columns is-mobile is-centered">
<div class="column is-half is-narrow"></div>
</div>
<footer>
<div class="box cta">
    <div class="columns is-mobile is-centered">
        <div class="field is-grouped is-grouped-multiline">
            <div class="control">
                <div class="tags has-addons"><a class="tag is-link" href="https://github.com/dansup/bulma-templates">Bulma Templates</a><span class="tag is-light">Daniel Supernault</span></div>
            </div>
            <div class="control">
                <div class="tags has-addons"><a class="tag is-link">The source code is licensed</a><span class="tag is-light">MIT  <i class="fa fa-github"></i></span></div>
            </div>
        </div>
    </div>
</div>
</footer>
<script src="../js/bulma.js"></script>
</body>
</html>

cluster/compropj/clienteapp/templates/clienteapp/landing.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Combos y Promociones</title>
    <link rel="shortcut icon" href="{% static 'clienteapp/images/fav_icon.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <!-- Bulma Version 0.7.1-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'clienteapp/css/landing.css' %}">
</head>

<body>
    <section class="hero is-info is-fullheight">
        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div class="navbar-brand">
                        <a class="navbar-item" href="../">
                            <img src="http://bulma.io/images/bulma-type-white.png" alt="Logo">
                        </a>
                        <span class="navbar-burger burger" data-target="navbarMenu">
                            <span></span>
                            <span></span>
                            <span></span>
                        </span>
                    </div>
                    <div id="navbarMenu" class="navbar-menu">
                        <div class="navbar-end">
                                {% if user.is_authenticated %}
                                <span class="navbar-item"> 
                                You are logged in as {{ user }}.
                                <a href="/accounts/logout/">Click here to log out.</a>
                                </span>
                            <span class="navbar-item">
                                <a class="button is-white is-outlined" href="#">
                                    <span class="icon">
                                        <i class="fa fa-home"></i>
                                    </span>
                                    <span>Home</span>
                                </a>
                            </span>
                            {% else %}
                            <span class="navbar-item">
                                <a class="button is-white is-outlined" href="{% url 'users_path:login' %}">
                                    <span class="icon">
                                        <i class="fa fa-superpowers"></i>
                                    </span>
                                    <span>Login</span>
                                </a>
                            </span>
                            <span class="navbar-item">
                                <a class="button is-white is-outlined" href="{% url 'users_path:registro_view' %}">
                                    <span class="icon">
                                        <i class="fa fa-book"></i>
                                    </span>
                                    <span>Registro</span>
                                </a>
                            </span>
                            {% endif %}
                            
                        

                        </div>
                    </div>
                </div>
            </nav>
            </div>

            <div class="hero-body">
                <div class="container has-text-centered">
                    <div class="column is-6 is-offset-3">
                        <h1 class="title">
                            Fase 1 de construcción.
                        </h1>
                        <h2 class="subtitle">
                            Pronto encontraras los mejores combos y promociones. Todo, aquí, ¡En un mismo lugar!, esperanos...
                        </h2>
                        {% if user.is_authenticated %}
                        <div class="box">
                            
                                    <a class="button is-info is-large" href="{% url 'users_path:cc_view' %}">
                                        Centros Comerciales
                                    </a>
                                
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>

    </section>
    <script async type="text/javascript" src="{% static 'clienteapp/js/bulma.js' %}"></script>
</body>

</html>

cluster/compropj/clienteapp/templates/clienteapp/login.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'clienteapp/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'clienteapp/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'clienteapp/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'clienteapp/fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'clienteapp/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'clienteapp/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'clienteapp/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'clienteapp/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'clienteapp/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'clienteapp/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'clienteapp/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

		{% if form.errors %}
		<p>Your username and password didn't match. Please try again.</p>
		{% endif %}
		
	<div class="limiter">
		<div class="container-login100" style="background-image: url('{% static 'clienteapp/images/bg-01.jpg' %}');">
			<div class="wrap-login100">

				<form method="post" action="{% url 'users_path:login' %}" >{% csrf_token %}
					<span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>

					<span class="login100-form-title p-b-34 p-t-27">
						Log in
					</span>

					<div >
						
						
					{{ form.username.label_tag }}
					{{ form.username }}
						
					</div>

					<div >
						
						<td>{{ form.password.label_tag }}</td>
    					<td>{{ form.password }}</td>
						
					</div>

					<br>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>


					<div class="text-center p-t-90">
						<a class="txt1" href="#">
							Forgot Password?
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static 'clienteapp/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'clienteapp/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'clienteapp/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'clienteapp/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'clienteapp/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'clienteapp/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'clienteapp/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'clienteapp/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'clienteapp/js/main.js' %}"></script>

</body>
</html>

cluster/compropj/clienteapp/templates/registrar/clienteapp/landing.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Combos y Promociones</title>
    <link rel="shortcut icon" href="{% static 'clienteapp/images/fav_icon.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <!-- Bulma Version 0.7.1-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'clienteapp/css/landing.css' %}">
</head>

<body>
    <section class="hero is-info is-fullheight">
        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div class="navbar-brand">
                        <a class="navbar-item" href="../">
                            <img src="http://bulma.io/images/bulma-type-white.png" alt="Logo">
                        </a>
                        <span class="navbar-burger burger" data-target="navbarMenu">
                            <span></span>
                            <span></span>
                            <span></span>
                        </span>
                    </div>
                    <div id="navbarMenu" class="navbar-menu">
                        <div class="navbar-end">
                                {% if user.is_authenticated %}
                                <span class="navbar-item"> 
                                You are logged in as {{ user }}.
                                <a href="/accounts/logout/">Click here to log out.</a>
                                </span>
                            <span class="navbar-item">
                                <a class="button is-white is-outlined" href="#">
                                    <span class="icon">
                                        <i class="fa fa-home"></i>
                                    </span>
                                    <span>Home</span>
                                </a>
                            </span>
                            {% else %}
                            <span class="navbar-item">
                                <a class="button is-white is-outlined" href="{% url 'users_path:login' %}">
                                    <span class="icon">
                                        <i class="fa fa-superpowers"></i>
                                    </span>
                                    <span>Login</span>
                                </a>
                            </span>
                            <span class="navbar-item">
                                <a class="button is-white is-outlined" href="{% url 'users_path:registro_view' %}">
                                    <span class="icon">
                                        <i class="fa fa-book"></i>
                                    </span>
                                    <span>Registro</span>
                                </a>
                            </span>
                            {% endif %}
                            
                        

                        </div>
                    </div>
                </div>
            </nav>
            </div>

            <div class="hero-body">
                <div class="container has-text-centered">
                    <div class="column is-6 is-offset-3">
                        <h1 class="title">
                            En construcción.
                        </h1>
                        <h2 class="subtitle">
                            Pronto encontraras los mejores combos y promociones. Todo, aquí, ¡En un mismo lugar!, esperanos...
                        </h2>
                        
                        <div class="box">
                            <div class="field is-grouped">
                                <p class="control is-expanded">
                                    <input class="input" type="text" placeholder="Enter your email">
                                </p>
                                <p class="control">
                                    <a class="button is-info">
                                        Noficame
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

    </section>
    <script async type="text/javascript" src="{% static 'clienteapp/js/bulma.js' %}"></script>
</body>

</html>