genericsitio/aplicacion/urls.py
from django.urls import path

from . import views

app_name='appli'
urlpatterns = [
    path('', views.IndexView.as_view(),name='index'),
    path('<int:pk>/',views.DetallesView.as_view(),name='detalles'),
    path('<int:pk>/resultados/', views.ResultadosView.as_view(), name='resultados'),
    path('<int:id_pregunta>/votar/', views.votar, name='votar'),
]   

genericsitio/cuentas/urls.py
from django.urls import path

from . import views

app_name='cuent'
urlpatterns = [
    path('login/', views.entrar_views,name='entrar_views'),
]  

genericsitio/genericsitio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('aplicaciones/', include('aplicacion.urls')),
    path('cuenta/', include('cuentas.urls')),
]

genericsitio/aplicacion/models.py
from django.db import models

# Create your models here.

class pregunta(models.Model):
    pregunta_texto= models.CharField(max_length=100)
    pub_calendario= models.DateTimeField('Fecha de publicacion')
    def __str__(self):
        return self.pregunta_texto

class eleccion(models.Model):
    preguntas= models.ForeignKey(pregunta,on_delete=models.CASCADE)
    eleccion_texto= models.CharField(max_length=100)
    votos= models.IntegerField(default=0)
    def __str__(self):
        return self.eleccion_texto
    

genericsitio/cuentas/models.py
from django.db import models

# Create your models here.

genericsitio/aplicacion/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect #agregado por mi
from .models import pregunta, eleccion
from django.template import loader #para usar index.html
from django.http import Http404
from django.urls import reverse
from django.views import generic
# Create your views here.


class IndexView(generic.ListView):
    template_name='aplicacion/index.html'
    context_object_name = 'listar_ultimas_preguntas'
    def get_queryset(self):
        return pregunta.objects.order_by('-pub_calendario')[:5]

class DetallesView(generic.DetailView):
    model=pregunta
    template_name="aplicacion/detalles.html"

class ResultadosView(generic.DetailView):
    model=pregunta
    template_name="aplicacion/resultados.html"


def votar(request, id_pregunta):
    preguntas = get_object_or_404(pregunta, pk=id_pregunta)
    print("id: ", id_pregunta)
    try:
         
        print("holi")
        
        opcion_seleccionada = preguntas.eleccion_set.get(pk=request.POST['elecciones'])
        
    except (KeyError, eleccion.DoesNotExist):
        print(KeyError, eleccion.DoesNotExist)
        print("holi2")
        return render(request, 'aplicacion/detalles.html',{'pregunta':preguntas,
        'error_message':"No seleccionaste nada bitch!", 
        })
    else:
        print("holi3")
        opcion_seleccionada.votos +=1
        opcion_seleccionada.save()
        return HttpResponseRedirect(reverse('appli:resultados', args=(preguntas.id,)))
        #return HttpResponse("Estas votando: %s" %id_pregunta) 

genericsitio/cuentas/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, get_user_model,login,logout
# Create your views here.
from . formulario import UsuarioLoginForm

def entrar_views(request):
    formulario=UsuarioLoginForm(request.POST or None)
    if request.user.is_authenticated:
        print("Log in")
    if formulario.is_valid():
        print("isvalid")
        usuario=formulario.cleaned_data.get("NombreUsuario")
        contrasena=formulario.cleaned_data.get("Contrasena")
        user=authenticate(username=usuario,password=contrasena)
        print("isvalid1")
        login(request,user)
    print("El formulario es invalido")    
    return render(request, "cuentas/entrarlogin.html", {"formulario":formulario})

def registrar_views(request):
    return render(request, "index.html", {})
    
def salir_views(request):
    return render(request, "index.html", {})

genericsitio/aplicacion/templates/aplicacion/detalles.html
<h1>{{pregunta.pregunta_texto}}</h1>

{% if error_message %}
<p><strong{{ error_message }}></strong></p>
{% endif %}

<form action="{% url 'appli:votar' pregunta.id %}" method="POST">

        {% csrf_token %}
        {% for elecciones in pregunta.eleccion_set.all %}
                <input type="radio" name="elecciones" id= "elecciones{{ forloop.counter }}" value="{{ elecciones.id }}"/>
                <label for="elecciones{{ forloop.counter }}">{{ elecciones.eleccion_texto }}</label>
                <p>Paso de loop: {{ forloop.counter }}</p>
                <p>Valor: {{ elecciones.id }}</p>
                <p>Array eleccion: elecciones{{ forloop.counter }}</p>
        <!-- El id toma el valor de eleccion1, eleccion2, eleccion3, etc, por cada paso
                del for. Por eso, el label se pone para cada id, es decir, para esa id 
                del paso del for. -->
        {% endfor %}
        <input type="submit" value="Votarr" />

</form>


<h1>Cambio anterior: </h1>

<ul>
        {% for eleccion in pregunta.eleccion_set.all %}
        <li>{{eleccion.eleccion_texto}}</li>
        {% endfor %}
</ul>


<a href="{% url 'appli:index' %}">Ir a Origen</a>

genericsitio/aplicacion/templates/aplicacion/index.html
{% load static %}
<link rel= "stylesheet" type= "text/css" href="{% static 'aplicacion/style.css' %}" />



{% if listar_ultimas_preguntas %}

    <ul>
        {% for pregunta in listar_ultimas_preguntas %}
            <li>
              <!--  <a href = "/polls/{{pregunta.id}}/"> {{pregunta.pregunta_texto}}</a>-->
                <!-- Por cada pregunta listada, se muestra como link que -->
                <!-- lleva al id de la pregunta con href -->
             <a href= "{% url 'appli:detalles' pregunta.id %}">{{pregunta.pregunta_texto}}</a>
            <!--Lo anterior resuelve el problema de direccionamiento--> 
            </li>
        {% endfor %}

    </ul>

{% else %}
    <p>No polls available.</p>
{% endif %}

genericsitio/aplicacion/templates/aplicacion/resultados.html
<h1> {{ pregunta.pregunta_texto }}</h1>
<ul>
    {% for elecciones in pregunta.eleccion_set.all %}
    <li>
        {{ elecciones.eleccion_texto }} -- {{ elecciones.votos }} vot{{ elecciones.votos|pluralize }}
    </li>
    {% endfor %}
</ul>

<a href="{% url 'appli:detalles' pregunta.id %}">Votar de nuevo</a>

genericsitio/cuentas/templates/cuentas/entrarlogin.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Django Login Service</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
{% load static %}
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'cuentas/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->


<!--===============================================================================================-->

<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'cuentas/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	
<!--===============================================================================================-->	

<!--===============================================================================================-->
	
<!--===============================================================================================-->
	
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'cuentas/util.css' %}">
<!--===============================================================================================-->
	
	<link rel="stylesheet" type="text/css" href="{% static 'cuentas/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-image: url('{% static 'cuentas/images/bg-01.jpg' %}');">
			<div class="wrap-login100 p-t-30 p-b-50">
				<span class="login100-form-title p-b-41">
					¡Bienvenido!
				</span>
				<form class="login100-form validate-form p-b-33 p-t-5" method="POST" >
					
{% csrf_token %}

					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						<input class="input100" type="text" name="username" placeholder="Usuario">
						<span class="focus-input100" data-placeholder="&#xe82a;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input class="input100" type="password" name="pass" placeholder="Contraseña">
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>

					<div class="container-login100-form-btn m-t-32">
						<button class="login100-form-btn">
							Entrar
						</button>
					</div>

				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->

<!--===============================================================================================-->

<!--===============================================================================================-->
	
<!--===============================================================================================-->
	
<!--===============================================================================================-->

<!--===============================================================================================-->

<!--===============================================================================================-->
	<script src="{% static 'cuentas/js/main.js' %}"></script>

</body>
</html>