watson/visualrec/urls.py
from django.urls import path
from . import views
from visualrec.views import AuthorDelete
app_name='appvr'
urlpatterns = [
    #http://127.0.0.1:8000/miwatson/publicar
    path('publicar/', views.index, name='inicio'),
    # http://127.0.0.1:8000/miwatson/visualizar/<id del producto>
    path('visualizar/<int:id_producto>', views.ver_item_view, name='visualizar'),
    #
    # http://127.0.0.1:8000/miwatson/login/
    path('login/',views.ingresar,name='login'),
    path('logout/',views.salido,name='logout'),
    # http://127.0.0.1:8000/miwatson/listar/
    path('listar/',views.listar, name='listar'),
    path('registrar/',views.registrar_view,name='registrar'),
    path('servicio_web/', views.servicio_web,name='servicio'),
    #en clases usamos pk
    path('eliminar/<int:pk>',AuthorDelete.as_view(), name='eliminar')

]

watson/watson/urls.py
from django.contrib import admin
from django.urls import path, include
'''se agrega [1] junto a [2] para hacer funcionar la carga de imagenes.'''
from django.conf.urls.static import static #[1]
from django.conf import settings #[1]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('miwatson/', include('visualrec.urls')),
    path('webservices/', include('webservices.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #[2]

watson/visualrec/models.py
from django.db import models

# Create your models here.
class venta_articulo(models.Model):
    titulo = models.CharField(max_length=25)
    analisis= models.CharField(max_length=20, default='', blank=True) #Como ya hay elementos en la base
    analiticas= models.TextField(default='', blank=True) #es necesario colocar un default
    precio = models.IntegerField(default=0)
    CARROS_MARCAS = (
        ('Bmw', 'CarroBmw'),
        ('Volkswagen', 'CarroVolkswagen'),
        ('Chevrolet', 'CarroChevrolet'),
        ('Ford', 'CarroFord'),
        ('Nissan', 'CarroNissan'),
    )
    marca_carros= models.CharField(max_length=10, choices=CARROS_MARCAS)
    descripcion=models.TextField()
    foto=models.ImageField(blank=True)

    def __str__(self):
        return self.titulo+' '+str(self.id)

watson/visualrec/forms.py
from django.forms import ModelForm, TextInput, NumberInput, ChoiceField, Textarea, Select, FileInput
from .models import venta_articulo
from django import forms
from django.contrib.auth.models import User #para registrar usuarios.
class articuloForm(ModelForm):
    class Meta:
        model= venta_articulo
        fields= ['titulo', 'precio', 'marca_carros', 'descripcion', 'foto']
        #fields = ('',)
        widgets = {'titulo': TextInput(attrs={'class':'input','placeholder':'titulo'}),
                   'precio': NumberInput(attrs={'class':'input','value':0}),
                   'marca_carros':Select(attrs={'class':'select'}),
                   'descripcion': Textarea(attrs={'class':'textarea','placeholder':'Descripción',}),
                   'foto':FileInput()}


class login_form(forms.Form):
    usuario=forms.CharField(widget=forms.TextInput())
    clave=forms.CharField(widget=forms.PasswordInput(render_value=False))

class registrar_usuario_form(forms.Form):
    usuario =   forms.CharField(widget=forms.TextInput())
    correo  =   forms.EmailField(widget=forms.TextInput())
    password_1  =  forms.CharField(label='Password',widget=forms.PasswordInput(render_value=False))
    password_2  =  forms.CharField(label='Confirmar Password',widget=forms.PasswordInput(render_value=False))
    
    def clean_usuario(self):
        usuario=self.cleaned_data['usuario']
        try:
            usr=User.objects.get(username=usuario)
        except User.DoesNotExist:
            return usuario
        raise forms.ValidationError('Nombre de usuario ya registrado')

    def clean_correo(self):
        correo = self.cleaned_data['correo']
        try:
            correo= User.objects.get(email=correo)
        except User.DoesNotExist:
            return correo
        raise forms.ValidationError('Correo Electrónico ya registrado')

    def clean_password_2(self):
        password_1=self.cleaned_data['password_1']
        password_2=self.cleaned_data['password_2']

        if password_1==password_2:
            pass
        else:
            raise forms.ValidationError('Las passwords no coinciden')
        

watson/visualrec/views.py
from django.shortcuts import render, redirect
from .models import venta_articulo
from .forms import articuloForm
from .forms import login_form
from .forms import registrar_usuario_form
from django.contrib.auth import login,logout, authenticate #para efectos de logeo.
from django.contrib.auth.models import User #para registrar usuarios.
#crear servicios web.
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers


# Create your views here.

#libreria de watson Fase3
import json
from watson_developer_cloud import VisualRecognitionV3 as VR
ApiVr = VR(version='2018-03-19',iam_api_key='0hKBk-h8hhOi9631MeFlabx28WF8N3XWMYq0DeKUNM_U')
#

def index(request):
    #espacio para el if post
    if request.method == 'POST':
        print(request.POST)
        form=articuloForm(request.POST, request.FILES)
        
        formTemporal=form.save(commit=False) #Con esto obtengo el objeto, luego puedo acceder
                                        #a los atributos de la forma tipica.
        #formTemporal.analisis="Holi" #Redefinicion de los atributos.
        formTemporal.analiticas="Holix2" #Redefinicion de los atributos.
        

        #clasificar imagen
        clase,valor = clasificarImagen(request.FILES['foto'])
        #print(clase,valor)

        formTemporal.analisis=str(clase) + " : " + str(valor) #Redefinicion de los atributos.


        #clasificar  descripcion.

        formTemporal.save()

        '''
        Antes de guardar el archivo, podría ubicar un nuevo atributo en la clase de tal forma
        que la validacion se haga al publicarse y no al listarse cada vez en la pagina.

        Si la validacion se hace al publicarse entonces debe haber un nuevo atributo llamado validacion.
        Este atributo contiene el analisis de la imagen.
        '''
      
    #cuando ocurre un get, osea cuando ingresamos a la pagina

    #Espacio para la instacia de articuloform
    inhtmlform = articuloForm()
    articulos = venta_articulo.objects.all()


    
    #el objeto que esta en la bd
    context={'objeto':inhtmlform, 'articulo':articulos }

    return render(request, 'visualrec/index.html', context)

def clasificarImagen(imagenTarget):
    resultadoClasif = ApiVr.classify(imagenTarget, threshold='0.6',classifier_ids='DefaultCustomModel_152343211')
    jsonresult = json.dumps(resultadoClasif,indent=2)
    #print(type(jsonresult))
    with open("data_file.json", "w") as write_file:
        json.dump(resultadoClasif, write_file)

    #print(jsonresult)
    #print(resultadoClasif)
    try:
        #print("Clase: ",resultadoClasif['images'][0]['classifiers'][0]['classes'][0]['class'])
        #print("Porcentaje: ",resultadoClasif['images'][0]['classifiers'][0]['classes'][0]['score'])
        clase = resultadoClasif['images'][0]['classifiers'][0]['classes'][0]['class']
        valor= resultadoClasif['images'][0]['classifiers'][0]['classes'][0]['score']
    except Exception as e:
        print(e)
    #print("Porcentaje: ",jsonresult['images'][0]['classifiers'][0]['classes'][0]['score']) No funciona
    return clase,valor

def clasificarDescripcion():
    pass

def ver_item_view(request, id_producto):
    #obj=articuloForm.objetcs.get(id=id_producto)
    
    try:
        #id_producto=1
        obj = venta_articulo.objects.get(id=id_producto)   
        #articulos = venta_articulo.objects.all()
        #print(articulos)
        #obj=articulos[id_producto]
        #print(obj)

    except Exception as e:
        print("La consulta no exite", e)
        msj="Error en la consulta, no existe el item."
    return render(request, 'visualrec/ver_item.html', locals())

def ingresar(request):
    
    if request.method=='POST':
        formulario=login_form(request.POST)
        if formulario.is_valid():
            user=formulario.cleaned_data['usuario']
            passw=formulario.cleaned_data['clave']
            usuario=authenticate(username=user,password=passw)
            if usuario is not None and usuario.is_active:
                login(request,usuario)
                return redirect('/miwatson/publicar/')
            else:
                msj="No se pudo iniciar sesion."
    formulario=login_form()
    return render(request,'visualrec/login.html',locals())


def salido(request):
    logout(request)
    return redirect('/miwatson/login/')
    #return render(request,'visualrec/logout.hml',locals())

def listar(request):
    inhtmlform = articuloForm()
    articulos = venta_articulo.objects.all()
    #el objeto que esta en la bd
    context={'objeto':inhtmlform, 'articulo':articulos }
    return render(request, 'visualrec/listar.html', context)

def registrar_view(request):
    formulario=registrar_usuario_form()
    if request.method=='POST':
        formulario=registrar_usuario_form(request.POST)
        if formulario.is_valid():
            usuario=formulario.cleaned_data['usuario']
            correo=formulario.cleaned_data['correo']
            password_1=formulario.cleaned_data['password_1']
            password_2=formulario.cleaned_data['password_2']
            usr=User.objects.create_user(username=usuario, email=correo, password=password_1)
            usr.save()
            return render(request, 'visualrec/gracias_por_registrarse.html')
        else:
            return render(request,'visualrec/registrar.html',locals())
    return render(request, 'visualrec/registrar.html', locals())

def servicio_web(request):
    #data=serializers.serialize('json', venta_articulo.objects.filter(status=True))
    data=serializers.serialize('json', venta_articulo.objects.all())
    return HttpResponse(data,content_type='application/json')


from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView

class AuthorDelete(DeleteView):
    model = venta_articulo
    success_url = reverse_lazy('appvr:listar')

watson/visualrec/templates/visualrec/gracias_por_registrarse.html
{% block titulo %}
Gracias por registrarse
{% endblock titulo %}
{% block contenido %}
<h1>Gracias por registrase</h1>
<a href="{% url 'appvr:inicio' %}">Inicio</a>
{% endblock contenido %}

watson/visualrec/templates/visualrec/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>AwesomeDjango</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css" />
    <script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js"></script>
    <script>
        function myFunction() {
            console.log("Holi")
            var file = document.getElementById("file");
            file.onchange = function () {
                if (file.files.length > 0) {

                    document.getElementById('filename').innerHTML = file.files[0].name;

                }
            };
        }
    </script>
</head>

<body>
    <section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    Aplicación Django + Visual Recognition + NLU
                </h1>

                {% if request.user.is_authenticated %}
                <li> <a href="{% url 'appvr:logout' %}" > Logout</a></li>
                <a href="{% url 'appvr:listar' %}">Solo listar</a>
                {% else %}
                <li> <a href="{% url 'appvr:login' %}" > Login</a></li>
                {% endif %}

            </div>
        </div>

    </section>

    </br> <!--Salto de linea-->

    <div class="tile is-ancestor">

        
        {% if request.user.is_authenticated %}
        <div class="tile is-parent">
            <article class="tile is-child notification is-info">
                <div class="content">
                    <p class="title">Publicar Articulo</p>
                    <p class="subtitle">Bienvenido, llena el registro.</p>
                    
                   
                    <div class="content">
                        <!-- Content -->


                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}

                        <div class="field">
                            <label class="label">Titulo</label>
                            <div class="control">
                            <!--    <input class="input" type="text" placeholder="Titulo"> -->
                                {{ objeto.titulo }} 
                            </div>
                        </div>

                        <div class="field">
                            <label class="label">Precio</label>
                            <div class="control has-icons-left has-icons-right">
                              <!--  <input class="input is-success" type="text" placeholder="Precio"> -->
                                {{ objeto.precio }}
                                <span class="icon is-small is-right">
                                    <i class="fas fa-check"></i>
                                </span>
                            </div>

                        </div>



                        <div class="field">
                            <label class="label">Marca</label>
                            <div class="control">
                                <div class="select">
                                    {{ objeto.marca_carros }} <!--
                                    <select>
                                        <option>Bmw</option>
                                        <option>Wolkswaggen</option>
                                        <option>Chevrolet</option>
                                        <option>Ford</option>
                                    </select> -->
                                </div>
                            </div>
                        </div>

                        <div class="field">
                            <label class="label">Descripción</label>
                            <div class="control">
                              <!--  <textarea class="textarea" placeholder="Descripción"></textarea> -->
                                {{ objeto.descripcion }}
                            </div>
                        </div>

                        {{ objeto.foto }}

                        <div class="field">
                            <div class="file is-primary">
                                <label class="file-label">
                                        
                                    <!--<input class="file-input" type="file" name="resume" onclick="myFunction()" id="file">
                                    
                                    <span class="file-cta">
                                        <span class="file-icon">
                                            <i class="fas fa-upload"></i>
                                        </span>
                                        <span class="file-label" id="filename">
                                            Subir
                                        </span>
                                    </span> -->
                                </label>
                            </div>
                        </div>
                        </br>

                        <div class="field is-grouped ">
                            <div class="control is">
                                <button type="submit" class="button is-success">Submit</button>
                            </div>

                            <div class="control">
                                <button class="button is-text">Cancel</button>
                            </div>
                        </div>


                    </form>




                        <!--fin content-->
                    </div>
                </div>
            </article>
        </div>
        
        {% endif %}

        



        <!--Tile de la derecha-->
        <div class="tile is-parent">
            <article class="tile is-child notification is-success">
                <div class="content">
                    <p class="title">Articulos Publicados</p>
                    <p class="subtitle">Descripcion de la ventas</p>
                    <div class="content">
                        <!-- Content -->
                        
                        {% for elemento in articulo %}
                          <div class="tile is-parent is-vertical">
                            <article class="tile is-child notification is-primary">
                              <p class="title is-1">{{ elemento.titulo }}, ${{ elemento.precio }}</p>
                              <p class="subtitle is-3">Vehículo {{ elemento.marca_carros }}</p>
                              <p class="subtitle is-4">"{{ elemento.descripcion }}"</p>
                              <img src="{{ elemento.foto.url }}" style="width:500px;height:320px"/>
                              <a href="{% url 'appvr:visualizar' id_producto=elemento.id %}">Ver item</a>
                              <p class="subtitle is-3">id: {{ elemento.id }}</p>
                            </article>
                          </div>
                        {% endfor %}
                        <!-- Fin content-->
                    </div>
                </div>
            </article>
        </div>

    </div>

    <footer class="footer">
    </footer>
</body>

</html>

watson/visualrec/templates/visualrec/listar.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>AwesomeDjango</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css" />
    <script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js"></script>
    <script>
        function myFunction() {
            console.log("Holi")
            var file = document.getElementById("file");
            file.onchange = function () {
                if (file.files.length > 0) {

                    document.getElementById('filename').innerHTML = file.files[0].name;

                }
            };
        }
    </script>
</head>

<body>
    <section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    Aplicación Django + Visual Recognition + NLU
                </h1>

                {% if request.user.is_authenticated %}
                <li> <a href="{% url 'appvr:logout' %}" > Logout</a></li>
                {% else %}
                <li> <a href="{% url 'appvr:login' %}" > Login</a></li>
                {% endif %}

            </div>
        </div>

    </section>

    </br> <!--Salto de linea-->

    <div class="tile is-ancestor">

        <!--Tile de la derecha-->
        <div class="tile is-parent">
            <article class="tile is-child notification is-success">
                <div class="content">
                    <p class="title">Articulos Publicados</p>
                    <a href="{% url 'appvr:inicio' %}">Inicio</a>
                    <p class="subtitle">Descripcion de la ventas</p>
                    <div class="content">
                        <!-- Content -->
                        
                        {% for elemento in articulo %}
                          <div class="tile is-parent is-vertical">
                            <article class="tile is-child notification is-primary">
                              <p class="title is-1">{{ elemento.titulo }}, ${{ elemento.precio }}</p>
                              <p class="subtitle is-3">Vehículo {{ elemento.marca_carros }}</p>
                              <p class="subtitle is-4">"{{ elemento.descripcion }}"</p>
                              
                              <a href="{% url 'appvr:visualizar' id_producto=elemento.id %}"><img src="{{ elemento.foto.url }}" style="width:500px;height:320px"/></a>
                              <p class="subtitle is-3">id: {{ elemento.id }}</p>

                              <a href="{% url 'appvr:eliminar' pk=elemento.id %}">Eliminar</a>


                            </article>
                          </div>

                        

                        {% endfor %}
                        <!-- Fin content-->
                    </div>
                </div>
            </article>
        </div>

    </div>

    <footer class="footer">
    </footer>
</body>

</html>

watson/visualrec/templates/visualrec/login.html
{% block titulo %}
Login
{% endblock titulo %}
{% block contenido %}
<form action="" method="POST">
{% csrf_token %}
{{ formulario }}
<input type="submit" name="login">
</form>
{% endblock contenido %}

watson/visualrec/templates/visualrec/registrar.html
{% block titulo %}
Registrar
{% endblock titulo %}

{% block contenido %}
<form action="" method="POST">
{% csrf_token %}
{{ formulario.as_p }}
<input type="submit" name="registrar">
</form>
{% endblock contenido %}

watson/visualrec/templates/visualrec/venta_articulo_confirm_delete.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" />
    </form>
</body>
</html>

watson/visualrec/templates/visualrec/ver_item.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
</head>

<body>
    <section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    Descripcion del articulo:  {{ obj.titulo }}
                </h1>
            </div>
        </div>
    </section>
    



    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    <div class="box">
                        <article class="media">
                            <div class="media-left">
                                <figure class="image is-50x50">
                                    <img src="http://openweathermap.org/img/w/10d.png" alt="Image">
                                </figure>
                            </div>
                            <div class="media-content">
                                <div class="content">
                                    <p>
                                        <span class="title">{{ obj.titulo }}</span>
                                        <br>
                                        <br> {{ obj.descripcion }}
                                    </p>
                                </div>
                            </div>
                        </article>
                        <a href="{% url 'appvr:inicio' %}">Inicio</a>

                        

                    </div>
                </div>
            </div>
        </div>
       
    </section>
   
    <footer class="footer">
    </footer>
</body>

</html>